INSERT INTO Features (FeatureId, FeatureName) VALUES
(NEWID(), 'Airbag'),
(NEWID(), 'ABS (Anti-lock Braking System)'),
(NEWID(), 'Traction Control'),
(NEWID(), 'Electronic Stability Program (ESP)'),
(NEWID(), 'Lane Departure Warning'),
(NEWID(), 'Blind Spot Monitoring'),
(NEWID(), 'Automatic Emergency Braking'),
(NEWID(), 'Adaptive Cruise Control'),
(NEWID(), 'Parking Assist'),
(NEWID(), 'Rear-View Camera'),
(NEWID(), '360° Camera System'),
(NEWID(), 'Heated Seats'),
(NEWID(), 'Ventilated Seats'),
(NEWID(), 'Leather Seats'),
(NEWID(), 'Sunroof / Panoramic Roof'),
(NEWID(), 'Automatic Climate Control'),
(NEWID(), 'Keyless Entry and Start'),
(NEWID(), 'Start/Stop Engine System'),
(NEWID(), 'Power Windows'),
(NEWID(), 'Navigation System'),
(NEWID(), 'Bluetooth Connectivity'),
(NEWID(), 'Apple CarPlay / Android Auto'),
(NEWID(), 'Heads-Up Display (HUD)'),
(NEWID(), 'Tire Pressure Monitoring System (TPMS)'),
(NEWID(), 'LED Headlights'),
(NEWID(), 'All-Wheel Drive (AWD)'),
(NEWID(), 'Front-Wheel Drive (FWD)'),
(NEWID(), 'Rear-Wheel Drive (RWD)'),
(NEWID(), 'Manual Transmission'),
(NEWID(), 'Automatic Transmission'),
(NEWID(), 'Continuously Variable Transmission (CVT)'),
(NEWID(), 'Electric Power Steering'),
(NEWID(), 'Cruise Control'),
(NEWID(), 'Multi-Function Steering Wheel'),
(NEWID(), 'Rain-Sensing Wipers'),
(NEWID(), 'Automatic Headlights'),
(NEWID(), 'Adjustable Suspension'),
(NEWID(), 'Engine Immobilizer'),
(NEWID(), 'Push-Button Start'),
(NEWID(), 'USB Port'),
(NEWID(), 'Hill-Start Assist'),
(NEWID(), 'Voice Command System'),
(NEWID(), 'Wireless Phone Charger'),
(NEWID(), 'Active Aerodynamics');